version: "3"
services:
  eval-api:
    build:
      dockerfile: ../dev.Dockerfile
      # context: ..
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace/eval-api:cached
    networks:
      - eval-network

networks:
  eval-network:
    driver: bridge
