name: Issue Trigger
on:
  issues:
    types:
      - opened
      - labeled
      - unlabeled
      - closed
      - unassigned
      - assigned
jobs:
  # Adds newly created issues onto project board in the default column 'New Issue Approval'
  # unless overridden when issue has "LA website bot" in title, then 'Questions / In Review'
  Add-Missing-Labels-To-Issues:
    runs-on: ubuntu-latest
    # Only trigger this action when an issue is newly created
    if: ${{ github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'transferred')}}
    steps:
      - uses: actions/checkout@v4
      # Check if the issue has required labels
      - name: Check Labels
        id: check-labels
        uses: actions/github-script@v7
        with:
          script: |
            const script = 'add missing label'
            console.log(script)
            return script

  #Asking for preliminary update when issue is assigned
  Ask-For-Preliminary-update:
    runs-on: ubuntu-latest
    #Triggers when the issue is newly assigned
    if: ${{ github.event_name == 'issues' && github.event.action == 'assigned'}}
    steps:
      - uses: actions/checkout@v4

      # Check if the issue has the required roles
      - name: Check Labels Prelim
        uses: actions/github-script@v7
        id: check-labels-prelim
        with:
          script: |
            const script = 'ask for update missing label'
            console.log(script)
            return script

  #   trigger for issues that are labeled and should be commented
  Add-New-Comment-For-Feature-Issue:
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'issues' && (github.event.action == 'labeled' && github.event.label.name == 'feature: feature branch')}}"
    env:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      issues: write
    steps:
      # uses checkout
      - uses: actions/checkout@v4
      # add comment
      - name: Add new label comment
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/issue-trigger/update-comments/add-comments.js')
            const addComment = script({g: github, c: context})
            return addComment
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
  # trigger to Hide a comment once label is removed
  Hide-Comment-For-Feature-Issue:
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'issues' && (github.event.action == 'unlabeled' && github.event.label.name == 'feature: feature branch')}}"
    permissions:
      issues: write
    steps:
      # uses checkout
      - uses: actions/checkout@v4
      # add comment
      - name: outdate the comment label
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/issue-trigger/update-comments/outdate-comments.js')
            const outdateComment = script({g: github, c: context})
            return outdateComment

  Test-Close-Issue:
    runs-on: ubuntu-latest
    if: "${{ github.event_name == 'issues' && github.event.action == 'closed' }}"
    permissions:
      issues: write
    steps:
      # uses checkout
      - uses: actions/checkout@v4
      # add comment
      - name: test issue close
        uses: actions/github-script@v7
        with:
          script: |
            console.log(github.event)
            console.log(context.payload.issue)
