name: Issue Comment Trigger
on:
  issue_comment:
    types:
      - created
jobs:
  # Adds newly created issues onto project board in the default column 'New Issue Approval'
  # unless overridden when issue has "LA website bot" in title, then 'Questions / In Review'
  Add-Commment-to-Prework_issue:
    runs-on: ubuntu-latest
    # Only trigger this action when an issue is newly created
    if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created'}}
    steps:
      - uses: actions/checkout@v4
      # Check if the issue has required labels
      - name: Check comment
        id: check-comment
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context.payload)
