name: Issue Comment Trigger
on:
  issue_comment:
    types:
      - created
jobs:
  # Adds newly created issues onto project board in the default column 'New Issue Approval'
  # unless overridden when issue has "LA website bot" in title, then 'Questions / In Review'
  Issue-Comment:
    runs-on: ubuntu-latest
    # Only trigger this action when an issue is newly created
    if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created'}}
    steps:
      - uses: actions/checkout@v4
      # Check if the issue has required labels
      - name: Check comment
        id: check-comment
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context.payload)

# context.payload VALUE

# {
#   action: 'created',
#   comment: {
#     author_association: 'OWNER',
#     body: 'test comment\r\n',
#     created_at: '2024-05-14T00:22:52Z',
#     html_url: 'https://github.com/partapparam/evalApi/issues/17#issuecomment-2109046151',
#     id: 2109046151,
#     issue_url: 'https://api.github.com/repos/partapparam/evalApi/issues/17',
#     node_id: 'IC_kwDOJyGIJc59tX2H',
#     performed_via_github_app: null,
#     reactions: {
#
#     },
#     updated_at: '2024-05-14T00:22:52Z',
#     url: 'https://api.github.com/repos/partapparam/evalApi/issues/comments/2109046151',
#     user: {
#       avatar_url: 'https://avatars.githubusercontent.com/u/24577323?v=4',
#       events_url: 'https://api.github.com/users/partapparam/events{/privacy}',
#       followers_url: 'https://api.github.com/users/partapparam/followers',
#       following_url: 'https://api.github.com/users/partapparam/following{/other_user}',
#       gists_url: 'https://api.github.com/users/partapparam/gists{/gist_id}',
#       gravatar_id: '',
#       html_url: 'https://github.com/partapparam',
#       id: 24577323,
#       login: 'partapparam',
#       node_id: 'MDQ6VXNlcjI0NTc3MzIz',
#       organizations_url: 'https://api.github.com/users/partapparam/orgs',
#       received_events_url: 'https://api.github.com/users/partapparam/received_events',
#       repos_url: 'https://api.github.com/users/partapparam/repos',
#       site_admin: false,
#       starred_url: 'https://api.github.com/users/partapparam/starred{/owner}{/repo}',
#       subscriptions_url: 'https://api.github.com/users/partapparam/subscriptions',
#       type: 'User',
#       url: 'https://api.github.com/users/partapparam'
#     }
#   },
#   issue: {
#     active_lock_reason: null,
#     assignee: {
#       avatar_url: 'https://avatars.githubusercontent.com/u/24577323?v=4',
#       events_url: 'https://api.github.com/users/partapparam/events{/privacy}',
#       followers_url: 'https://api.github.com/users/partapparam/followers',
#       following_url: 'https://api.github.com/users/partapparam/following{/other_user}',
#       gists_url: 'https://api.github.com/users/partapparam/gists{/gist_id}',
#       gravatar_id: '',
#       html_url: 'https://github.com/partapparam',
#       id: 24577323,
#       login: 'partapparam',
#       node_id: 'MDQ6VXNlcjI0NTc3MzIz',
#       organizations_url: 'https://api.github.com/users/partapparam/orgs',
#       received_events_url: 'https://api.github.com/users/partapparam/received_events',
#       repos_url: 'https://api.github.com/users/partapparam/repos',
#       site_admin: false,
#       starred_url: 'https://api.github.com/users/partapparam/starred{/owner}{/repo}',
#       subscriptions_url: 'https://api.github.com/users/partapparam/subscriptions',
#       type: 'User',
#       url: 'https://api.github.com/users/partapparam'
#     },
#     assignees: [ [Object] ],
#     author_association: 'OWNER',
#     body: null,
#     closed_at: null,
#     comments: 1,
#     comments_url: 'https://api.github.com/repos/partapparam/evalApi/issues/17/comments',
#     created_at: '2024-05-14T00:14:12Z',
#     events_url: 'https://api.github.com/repos/partapparam/evalApi/issues/17/events',
#     html_url: 'https://github.com/partapparam/evalApi/issues/17',
#     id: 2294071114,
#     labels: [],
#     labels_url: 'https://api.github.com/repos/partapparam/evalApi/issues/17/labels{/name}',
#     locked: false,
#     milestone: null,
#     node_id: 'I_kwDOJyGIJc6IvL9K',
#     number: 17,
#     performed_via_github_app: null,
#     reactions: {
#       '+1': 0,
#       '-1': 0,
#       confused: 0,
#       eyes: 0,
#       heart: 0,
#       hooray: 0,
#       laugh: 0,
#       rocket: 0,
#       total_count: 0,
#       url: 'https://api.github.com/repos/partapparam/evalApi/issues/17/reactions'
#     },
#     repository_url: 'https://api.github.com/repos/partapparam/evalApi',
#     state: 'open',
#     state_reason: null,
#     timeline_url: 'https://api.github.com/repos/partapparam/evalApi/issues/17/timeline',
#     title: 'GHA',
#     updated_at: '2024-05-14T00:22:53Z',
#     url: 'https://api.github.com/repos/partapparam/evalApi/issues/17',
#     user: {
#       avatar_url: 'https://avatars.githubusercontent.com/u/24577323?v=4',
#       events_url: 'https://api.github.com/users/partapparam/events{/privacy}',
#       followers_url: 'https://api.github.com/users/partapparam/followers',
#       following_url: 'https://api.github.com/users/partapparam/following{/other_user}',
#       gists_url: 'https://api.github.com/users/partapparam/gists{/gist_id}',
#       gravatar_id: '',
#       html_url: 'https://github.com/partapparam',
#       id: 24577323,
#       login: 'partapparam',
#       node_id: 'MDQ6VXNlcjI0NTc3MzIz',
#       organizations_url: 'https://api.github.com/users/partapparam/orgs',
#       received_events_url: 'https://api.github.com/users/partapparam/received_events',
#       repos_url: 'https://api.github.com/users/partapparam/repos',
#       site_admin: false,
#       starred_url: 'https://api.github.com/users/partapparam/starred{/owner}{/repo}',
#       subscriptions_url: 'https://api.github.com/users/partapparam/subscriptions',
#       type: 'User',
#       url: 'https://api.github.com/users/partapparam'
#     }
#   },
#   repository: {
#     allow_forking: true,
#     archive_url: 'https://api.github.com/repos/partapparam/evalApi/{archive_format}{/ref}',
#     archived: false,
#     assignees_url: 'https://api.github.com/repos/partapparam/evalApi/assignees{/user}',
#     blobs_url: 'https://api.github.com/repos/partapparam/evalApi/git/blobs{/sha}',
#     branches_url: 'https://api.github.com/repos/partapparam/evalApi/branches{/branch}',
#     clone_url: 'https://github.com/partapparam/evalApi.git',
#     collaborators_url: 'https://api.github.com/repos/partapparam/evalApi/collaborators{/collaborator}',
#     comments_url: 'https://api.github.com/repos/partapparam/evalApi/comments{/number}',
#     commits_url: 'https://api.github.com/repos/partapparam/evalApi/commits{/sha}',
#     compare_url: 'https://api.github.com/repos/partapparam/evalApi/compare/{base}...{head}',
#     contents_url: 'https://api.github.com/repos/partapparam/evalApi/contents/{+path}',
#     contributors_url: 'https://api.github.com/repos/partapparam/evalApi/contributors',
#     created_at: '2023-06-21T05:08:50Z',
#     default_branch: 'master',
#     deployments_url: 'https://api.github.com/repos/partapparam/evalApi/deployments',
#     description: 'Node/Express API for Eval - Where Service Providers Can Rate Homeowners',
#     disabled: false,
#     downloads_url: 'https://api.github.com/repos/partapparam/evalApi/downloads',
#     events_url: 'https://api.github.com/repos/partapparam/evalApi/events',
#     fork: false,
#     forks: 0,
#     forks_count: 0,
#     forks_url: 'https://api.github.com/repos/partapparam/evalApi/forks',
#     full_name: 'partapparam/evalApi',
#     git_commits_url: 'https://api.github.com/repos/partapparam/evalApi/git/commits{/sha}',
#     git_refs_url: 'https://api.github.com/repos/partapparam/evalApi/git/refs{/sha}',
#     git_tags_url: 'https://api.github.com/repos/partapparam/evalApi/git/tags{/sha}',
#     git_url: 'git://github.com/partapparam/evalApi.git',
#     has_discussions: false,
#     has_downloads: true,
#     has_issues: true,
#     has_pages: false,
#     has_projects: true,
#     has_wiki: false,
#     homepage: 'https://eval-app.com/',
#     hooks_url: 'https://api.github.com/repos/partapparam/evalApi/hooks',
#     html_url: 'https://github.com/partapparam/evalApi',
#     id: 656508965,
#     is_template: false,
#     issue_comment_url: 'https://api.github.com/repos/partapparam/evalApi/issues/comments{/number}',
#     issue_events_url: 'https://api.github.com/repos/partapparam/evalApi/issues/events{/number}',
#     issues_url: 'https://api.github.com/repos/partapparam/evalApi/issues{/number}',
#     keys_url: 'https://api.github.com/repos/partapparam/evalApi/keys{/key_id}',
#     labels_url: 'https://api.github.com/repos/partapparam/evalApi/labels{/name}',
#     language: 'JavaScript',
#     languages_url: 'https://api.github.com/repos/partapparam/evalApi/languages',
#     license: null,
#     merges_url: 'https://api.github.com/repos/partapparam/evalApi/merges',
#     milestones_url: 'https://api.github.com/repos/partapparam/evalApi/milestones{/number}',
#     mirror_url: null,
#     name: 'evalApi',
#     node_id: 'R_kgDOJyGIJQ',
#     notifications_url: 'https://api.github.com/repos/partapparam/evalApi/notifications{?since,all,participating}',
#     open_issues: 2,
#     open_issues_count: 2,
#     owner: {
#       avatar_url: 'https://avatars.githubusercontent.com/u/24577323?v=4',
#       events_url: 'https://api.github.com/users/partapparam/events{/privacy}',
#       followers_url: 'https://api.github.com/users/partapparam/followers',
#       following_url: 'https://api.github.com/users/partapparam/following{/other_user}',
#       gists_url: 'https://api.github.com/users/partapparam/gists{/gist_id}',
#       gravatar_id: '',
#       html_url: 'https://github.com/partapparam',
#       id: 24577323,
#       login: 'partapparam',
#       node_id: 'MDQ6VXNlcjI0NTc3MzIz',
#       organizations_url: 'https://api.github.com/users/partapparam/orgs',
#       received_events_url: 'https://api.github.com/users/partapparam/received_events',
#       repos_url: 'https://api.github.com/users/partapparam/repos',
#       site_admin: false,
#       starred_url: 'https://api.github.com/users/partapparam/starred{/owner}{/repo}',
#       subscriptions_url: 'https://api.github.com/users/partapparam/subscriptions',
#       type: 'User',
#       url: 'https://api.github.com/users/partapparam'
#     },
#     private: false,
#     pulls_url: 'https://api.github.com/repos/partapparam/evalApi/pulls{/number}',
#     pushed_at: '2024-05-14T00:22:26Z',
#     releases_url: 'https://api.github.com/repos/partapparam/evalApi/releases{/id}',
#     size: 157,
#     ssh_url: 'git@github.com:partapparam/evalApi.git',
#     stargazers_count: 0,
#     stargazers_url: 'https://api.github.com/repos/partapparam/evalApi/stargazers',
#     statuses_url: 'https://api.github.com/repos/partapparam/evalApi/statuses/{sha}',
#     subscribers_url: 'https://api.github.com/repos/partapparam/evalApi/subscribers',
#     subscription_url: 'https://api.github.com/repos/partapparam/evalApi/subscription',
#     svn_url: 'https://github.com/partapparam/evalApi',
#     tags_url: 'https://api.github.com/repos/partapparam/evalApi/tags',
#     teams_url: 'https://api.github.com/repos/partapparam/evalApi/teams',
#     topics: [],
#     trees_url: 'https://api.github.com/repos/partapparam/evalApi/git/trees{/sha}',
#     updated_at: '2024-05-14T00:22:11Z',
#     url: 'https://api.github.com/repos/partapparam/evalApi',
#     visibility: 'public',
#     watchers: 0,
#     watchers_count: 0,
#     web_commit_signoff_required: false
#   },
#   sender: {
#     avatar_url: 'https://avatars.githubusercontent.com/u/24577323?v=4',
#     events_url: 'https://api.github.com/users/partapparam/events{/privacy}',
#     followers_url: 'https://api.github.com/users/partapparam/followers',
#     following_url: 'https://api.github.com/users/partapparam/following{/other_user}',
#     gists_url: 'https://api.github.com/users/partapparam/gists{/gist_id}',
#     gravatar_id: '',
#     html_url: 'https://github.com/partapparam',
#     id: 24577323,
#     login: 'partapparam',
#     node_id: 'MDQ6VXNlcjI0NTc3MzIz',
#     organizations_url: 'https://api.github.com/users/partapparam/orgs',
#     received_events_url: 'https://api.github.com/users/partapparam/received_events',
#     repos_url: 'https://api.github.com/users/partapparam/repos',
#     site_admin: false,
#     starred_url: 'https://api.github.com/users/partapparam/starred{/owner}{/repo}',
#     subscriptions_url: 'https://api.github.com/users/partapparam/subscriptions',
#     type: 'User',
#     url: 'https://api.github.com/users/partapparam'
#   }
# }
