name: Issue Comment Trigger
on:
  issue_comment:
    types:
      - created
jobs:
  # Adds newly created issues onto project board in the default column 'New Issue Approval'
  # unless overridden when issue has "LA website bot" in title, then 'Questions / In Review'
  Add-Comment-To-Prework-Issue: # Only trigger this action when an issue comment is newly created
    if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created'}}
    permissions:
      issues: write
    uses: partapparam/evalApi/.github/workflows/reusable_comment_workflow.yaml@master
    secrets: inherit
