name: Pull Request Review Comment Trigger
on:
  pull_request_review_comment:
    types:
      - created
jobs:
  Pull-Request-Review-Comment:
    # Only trigger this action when an PR comment is created
    if: ${{ github.event_name == 'pull_request_review_comment' && github.event.action == 'created'}}
    permissions:
      issues: write
    uses: partapparam/evalApi/.github/workflows/reusable_comment_workflow.yaml@master
    secrets: inherit
