name: Pull Request Review Trigger
on:
  pull_request_review:
    types:
      - submitted
jobs:
  # Adds newly created issues onto project board in the default column 'New Issue Approval'
  # unless overridden when issue has "LA website bot" in title, then 'Questions / In Review'
  PR-Review:
    runs-on: ubuntu-latest
    # Only trigger this action when an issue is newly created
    if: ${{ github.event_name == 'pull_request_review' && github.event.action == 'submitted'}}
    steps:
      - uses: actions/checkout@v4
      # Check if the issue has required labels
      - name: Review Submitted
        id: review
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context.payload)
