name: Pull Request Review Trigger
on:
  pull_request_review:
    types:
      - submitted
jobs:
  # Adds newly created issues onto project board in the default column 'New Issue Approval'
  # unless overridden when issue has "LA website bot" in title, then 'Questions / In Review'
  PR-Review-Add-Prework-Comment:
    # Only trigger this action when an issue is newly created
    if: ${{ github.event_name == 'pull_request_review' && github.event.action == 'submitted'}}
    permissions:
      issues: write
    uses: partapparam/evalApi/.github/workflows/reusable_comment_workflow.yaml@master
