name: Pull Request Trigger
on:
  pull_request:
    types:
      - opened
      - closed
jobs:
  # Adds newly created issues onto project board in the default column 'New Issue Approval'
  # unless overridden when issue has "LA website bot" in title, then 'Questions / In Review'
  Add-Comment-To-Prework-Issue: # Only trigger this action when an issue is newly created
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'closed')}}
    permissions:
      issues: write
    uses: partapparam/evalApi/.github/workflows/reusable_comment_workflow.yaml@master
    secrets: inherit
