name: Pull Request Review Comment Trigger
on:
  pull_request_review_comment:
    types:
      - created
jobs:
  # Adds newly created issues onto project board in the default column 'New Issue Approval'
  # unless overridden when issue has "LA website bot" in title, then 'Questions / In Review'
  Pull-Request-Review-Commnet:
    runs-on: ubuntu-latest
    # Only trigger this action when an issue is newly created
    if: ${{ github.event_name == 'pull_request_review' && github.event.action == 'submitted'}}
    steps:
      - uses: actions/checkout@v4
      # Check if the issue has required labels
      - name: PR comment
        id: pr-comment
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context.payload)
