name: Find Prework Issue and Comment User Activity

on:
  workflow_call:

jobs:
  add-comment-to-prework-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Determine contributor generating activity
        id: get-contributor
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/get-activity-contributor.js')
            const value = script({g: github, c: context})
            console.log(value)

      - name: Get prework issue
        id: prework-issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/get-prework-issue.js')
            return script({g: github, c: context}, 'partapparam')

      - name: Update prework issue status
        id: prework-issue-status
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/update_prework_issue_status.js')
            const issue = ${{steps.prework-issue.outputs.result}}
            return script({g: github, c: context}, issue)

      - name: Leave comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/utils/post-issue-comment.js')
            const issue = ${{steps.prework-issue.outputs.result}}
            return script(issue.number, 'adding comment', github, context)
