name: Find Prework Issue and Comment User Activity

on:
  workflow_call:

jobs:
  add-comment-to-prework-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Get activity detail
        id: get-activity-detail
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/get-activity-contributor.js')
            const contributor = script({g: github, c: context})
            return contributor

      - name: Get prework issue
        id: prework-issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/get-prework-issue.js')
            const activityDetail = ${{steps.get-activity-detail.outputs.result}}
            console.log(activityDetail)
            return script({g: github, c: context}, activityDetail)

      - name: Update prework issue status
        id: prework-issue-status
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/update_prework_issue_status.js')
            const issue = ${{steps.prework-issue.outputs.result}}
            return script({g: github, c: context}, issue)

      - name: Move issue
        id: move-issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HFLA_PROJECT_BOARD_TOKEN }}
          script: |
            const projectColumnId = "PC_lATOLVwEr84A4jIbzgEvVeo"
            const mutation = `
              mutation ($cardId: ID! $columnId: ID!) {
                moveProjectCard (input: {cardId: $cardId columnId: $columnId}) {
                  cardEdge {
                    node {
                      resourcePath
                    }
                  }
              }
              }
              `
            const issue = ${{steps.prework-issue-status.outputs.result}}
            const data = await github.graphql(mutation, {
              cardId: issue.id,
              columnId: projectColumnId,
            })
            return data

      - name: Leave comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/add-prework-comment.js')
            const issue = ${{steps.prework-issue.outputs.result}}
            const activityDetail = ${{steps.get-activity-detail.outputs.result}}
            return script({ g: github, c: context}, issue.number, activityDetail)
