name: Find Prework Issue and Comment User Activity

on:
  workflow_call:

jobs:
  add-comment-to-prework-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get prework issue
        id: prework-issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/add_prework_issue_comment.js')
            return script({g: github, c: context}, 'partapparam')

      - name: Leave comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/utils/post-issue-comment.js')
            const issues = ${{steps.prework-issue.outputs.result}}
            return script(issues[0].number, 'adding comment', github, context)
    #   - name: Login to the Registry
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{secrets.registry_username}}
    #       password: ${{secrets.registry_password}}
