name: Find Prework Issue and Comment User Activity

on:
  workflow_call:

jobs:
  add-comment-to-prework-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Get prework issue
        id: prework-issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/get-prework-issue.js')
            script({g: github, c: context}, 'partapparam')

      - name: Update prework issue status
        id: preword-issue-status
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/prework_issue_comment/update_prework_issue_status.js')
            const issue = ${{steps.prework-issue.outputs.result}}
            script({g: github, c: context}, issue)

      - name: Leave comment on Issue
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./github-actions/utils/post-issue-comment.js')
            const issue = ${{steps.prework-issue.outputs.result}}
            script(issue.number, 'adding comment', github, context)
    #   - name: Login to the Registry
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{secrets.registry_username}}
    #       password: ${{secrets.registry_password}}
